#provision_type="local"
provision_type="full"
SHARED_mount_point="/vagrant"
# Update
nameserver="192.168.69.2"
# Update
redis_cluster_fqdn="rc1.example.com"
redis_cluster_admin="redis@redis.com"
redis_cluster_password="redis"

# Update
network_type="public_network"
#network_type="private_network"

ram_size=6144
cpu_count=4
# Update
hostname_prefix="rc1-rh8-node"
# Update
first_node_ip="192.168.69.101"
# Update
NODES = [
    { :hostname => hostname_prefix+"1", :ip => first_node_ip },
    { :hostname => hostname_prefix+"2", :ip => "192.168.69.102" },
    { :hostname => hostname_prefix+"3", :ip => "192.168.69.103" },
]

# Do not change below

setup_redis_env_vars=SHARED_mount_point+' '+redis_cluster_fqdn+' '+redis_cluster_admin+' '+redis_cluster_password+' '+first_node_ip

NODES.each do |node|
  system ('sh ../COMMON/VAGRANT_provision_prep.sh '+node[:hostname]+' ../../SHARED '+setup_redis_env_vars)
end

if provision_type == 'local'
  puts 'Provision only local Vagrant files. Exit.'
  abort
end

Vagrant.configure("2") do |config|
  NODES.each do |node|
    config.vm.define node[:hostname] do |server|
      server.vm.hostname = node[:hostname]
      server.vm.provider :virtualbox do |vb|
        vb.name    = node[:hostname]
        vb.memory = ram_size
        vb.cpus = cpu_count
      end
      server.vm.box = "generic/centos8s"
      server.vm.hostname = node[:hostname]
      server.vm.network network_type, ip: node[:ip]
      server.vm.synced_folder "../../SHARED", SHARED_mount_point
      server.vm.provision "redis-init", type: "shell", path: "../COMMON/setup_nodes.sh", args: nameserver
      server.vm.provision "redis-provision-prep", type: "shell", path: "../COMMON/REDIS_provision_prep.sh", args: [SHARED_mount_point, node[:hostname]]
      server.vm.provision "redis-install-bins", type: "shell", run: "never", path: "../COMMON/REDIS_install_bins.sh"
      server.vm.provision "redis-create-cluster", type: "shell", run: "never", path: "../COMMON/REDIS_create_cluster.sh"
      server.vm.provision "redis-uninstall-bins", type: "shell", run: "never", path: "../COMMON/REDIS_uninstall_bins.sh"
      server.vm.provision "yum-packages", type: "shell", run: "never", path: "../COMMON/setup_yum.sh"
    end
  end
end