NODES = [
{ :hostname => 'rc1-rh8-node1', :ip => '192.168.69.101' },
{ :hostname => 'rc1-rh8-node2', :ip => '192.168.69.102' },
{ :hostname => 'rc1-rh8-node3', :ip => '192.168.69.103' },
]
ENV_name="RC1RH8"
SHARED_mount_point="/root/SHARED"
redis_cluster_fqdn="rc1.example.com"
network_type="public_network"
ram_size="6144"
cpu_count="4"
Vagrant.configure("2") do |config|
  NODES.each do |node|
    #system ('sh ./'+node[:hostname]+'.'+redis_cluster_fqdn+'.sh')
    config.vm.define node[:hostname] do |server|
      server.vm.hostname = node[:hostname]
      server.vm.provider :virtualbox do |vb|
        vb.name    = node[:hostname]
        vb.memory = ram_size
        vb.cpus = cpu_count
      end
      server.vm.box = "generic/centos8s"
      server.vm.hostname = node[:hostname]
      server.vm.network network_type, ip: node[:ip]
      server.vm.synced_folder "../../SHARED", SHARED_mount_point
      server.vm.provision "shell", inline: "sed -i 's/^PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config;systemctl reload sshd"
      server.vm.provision "redis-provision-prep", type: "shell", run: "never", path: "../COMMON/REDIS_provision_prep.sh", args: [SHARED_mount_point, node[:hostname], ENV_name]
      server.vm.provision "redis-init", type: "shell", run: "never", path: "../COMMON/REDIS_nodes_init.sh"
      server.vm.provision "redis-install-bins", type: "shell", run: "never", path: "../COMMON/REDIS_install_bins.sh"
      server.vm.provision "redis-create-cluster", type: "shell", run: "never", path: "../COMMON/REDIS_create_cluster.sh"
      server.vm.provision "redis-uninstall-bins", type: "shell", run: "never", path: "../COMMON/REDIS_uninstall_bins.sh"
      server.vm.provision "redis-yum-packages", type: "shell", run: "never", path: "../COMMON/setup_yum.sh"
    end
  end
end
