NODES = [
{ :hostname => 'k8-8X-n1', :ip => '192.168.69.81' },
{ :hostname => 'k8-8X-n2', :ip => '192.168.69.82' },
{ :hostname => 'k8-8X-n3', :ip => '192.168.69.83' },
{ :hostname => 'k8-8X-n4', :ip => '192.168.69.84' },
]
ENV_name="K8-8X"
SHARED_mount_point="/root/SHRD"
network_type="public_network"
ram_size="8192"
cpu_count="8"
Vagrant.configure("2") do |config|
  NODES.each do |node|
    config.vm.define node[:hostname] do |server|
      server.vm.hostname = node[:hostname]
      server.vm.provider :virtualbox do |vb|
        vb.name    = node[:hostname]
        vb.memory = ram_size
        vb.cpus = cpu_count
      end
      server.vm.box = "generic/centos8s"
      server.vm.hostname = node[:hostname]
      server.vm.network network_type, ip: node[:ip]
      server.vm.synced_folder "../../SHARED", SHARED_mount_point
      server.vm.provision "k8-provision-prep", type: "shell", run: "never", path: "../COMMON/K8_provision_prep.sh", args: [SHARED_mount_point, node[:hostname], ENV_name]
      server.vm.provision "k8-init", type: "shell", run: "never", path: "../COMMON/K8_nodes_init.sh"
      server.vm.provision "k8-install-bins", type: "shell", run: "never", path: "../COMMON/K8_install_bins.sh"
      server.vm.provision "k8-create-cluster-cp", type: "shell", run: "never", path: "../COMMON/K8_create_cluster-cp.sh"
      server.vm.provision "k8-create-cluster-w", type: "shell", run: "never", path: "../COMMON/K8_create_cluster-w.sh"
      #server.vm.provision "k8-uninstall-bins", type: "shell", run: "never", path: "../COMMON/k8_uninstall_bins.sh"
      #server.vm.provision "k8-yum-packages", type: "shell", run: "never", path: "../COMMON/setup_yum.sh"
    end
  end
end
